In [59]:
import pandas as pd
import numpy as np

In [67]:
df=pd.read_csv('cardata.csv')
df = df.drop(['Owner','Present_Price'], axis=1)
df.sample(5)

,Car_Name,Year,Selling_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission
275,city,2016,10.90,30753,Petrol,Dealer,Automatic
293,city,2010,3.25,38000,Petrol,Dealer,Manual
289,city,2016,10.11,10980,Petrol,Dealer,Manual
232,elantra,2015,11.45,12900,Petrol,Dealer,Automatic
129,Yamaha FZ S V 2.0,2017,0.78,5000,Petrol,Individual,Manual

In [68]:
from sklearn.model_selection import train_test_split
x= df.drop(['Selling_Price'], axis =1)
y=df['Selling_Price']

X_train,X_test, Y_train , Y_test = train_test_split(x,y ,test_size = 0.2)
X_train

              Car_Name  Year  Kms_Driven Fuel_Type Seller_Type Transmission
217                eon  2016       15000    Petrol      Dealer       Manual
252               brio  2015       31427    Petrol      Dealer    Automatic
225                i10  2011       22517    Petrol      Dealer       Manual
127  Bajaj Avenger 150  2016        7000    Petrol  Individual       Manual
92              innova  2005       75000    Petrol      Dealer       Manual
..                 ...   ...         ...       ...         ...          ...
142   Yamaha FZ  v 2.0  2015       29000    Petrol  Individual       Manual
215              verna  2012       36100    Petrol      Dealer       Manual
24             wagon r  2013       56879    Petrol      Dealer       Manual
110          KTM RC200  2016        6000    Petrol  Individual       Manual
290              amaze  2014       19000    Petrol      Dealer       Manual

[240 rows x 6 columns]

### Using Pandas

In [69]:
pd.get_dummies(X_train[['Fuel_Type', 'Seller_Type', 'Transmission']])

,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Dealer,Seller_Type_Individual,Transmission_Automatic,Transmission_Manual
217,False,False,True,True,False,False,True
252,False,False,True,True,False,True,False
225,False,False,True,True,False,False,True
127,False,False,True,False,True,False,True
92,False,False,True,True,False,False,True
...,...,...,...,...,...,...,...
142,False,False,True,False,True,False,True
215,False,False,True,True,False,False,True
24,False,False,True,True,False,False,True
110,False,False,True,False,True,False,True
290,False,False,True,True,False,False,True

### Using Sklearn

In [63]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype = 'int32')
X_train_new = ohe.fit_transform(X_train[['Car_Name','Fuel_Type', 'Seller_Type','Transmission']])
X_test_new = ohe.fit(X_test[['Car_Name','Fuel_Type', 'Seller_Type','Transmission']])
X_train = np.hstack((X_train[['Year' , 'Kms_Driven']].values, X_train_new ))

array([[0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 1, 1]], shape=(240, 90), dtype=int32)

### Cars less than 10 will rename to others

In [70]:

counts=df['Car_Name'].value_counts()
df['Car_Name'].nunique()
threshold=10
repl = counts[counts <= threshold].index

pd.get_dummies(df[['Car_Name']].replace(repl, 'other'))

,Car_Name_city,Car_Name_corolla altis,Car_Name_fortuner,Car_Name_other,Car_Name_verna
0,False,False,False,True,False
1,False,False,False,True,False
2,False,False,False,True,False
3,False,False,False,True,False
4,False,False,False,True,False
...,...,...,...,...,...
296,True,False,False,False,False
297,False,False,False,True,False
298,True,False,False,False,False
299,True,False,False,False,False
300,False,False,False,True,False